extra-deps:
- webkitgtk3-0.13.1.3
resolver: lts-2.16
flags: {}
packages:
- '.'
- location:
    git: https://github.com/gtk2hs/gtk2hs.git
    commit: 72f1d60f76eaa6cad2c58c0409fdfe9fc88cde40
  subdirs:
  - pango
  - gtk
